### ISSUE TITLE
mod_enospc.c:116: undefined reference to `HANDLED'

### ISSUE THREAD

**Issue by Mimikoo** [Castaglia/proftpd-mod_enospc#1]
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: modules/mod_enospc.o: in function `set_enospcthreshold':
/src/proftpd/modules/mod_enospc.c:116: undefined reference to `HANDLED'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: modules/mod_enospc.o: in function `set_enospcengine':
/src/proftpd/modules/mod_enospc.c:88: undefined reference to `HANDLED'

**Comment by Castaglia** [comment]
Can you please provide the full list of steps/commands you're running, to encounter this error?

**Comment by Castaglia** [comment]
This build error should now be fixed in `master`.  Care to try again?
